### ISSUE TITLE
Switch from Oracle JDK to OpenJDK

### ISSUE THREAD

**Issue by kltm** [cmungall/go-graphstore#13]
Looking at the travis, it looks like `oraclejdk8` is being used.

Since all production is done on openjdk, this should be switched to openjdk as well.

**Comment by balhoff** [comment]
Two things: the Travis file is trying to run as a Java project, I guess because there is a `pom.xml`. But that POM is only there in order to download the Blazegraph jar (there isn't really a Java project). But also, Travis doesn't seem to support OpenJDK 8: https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs

Also: https://github.com/travis-ci/travis-ci/issues/6483

**Comment by cmungall** [comment]
Yep, we have no other option here; some of our other projects:

https://github.com/search?q=org%3Aobophenotype+oraclejdk8&type=Code

https://github.com/search?q=org%3Ageneontology+oraclejdk8&type=Code

https://github.com/search?utf8=%E2%9C%93&q=org%3APlanteome+oraclejdk8&type=Code&ref=searchresults

https://github.com/search?utf8=%E2%9C%93&q=org%3Aontodev+oraclejdk8&type=Code&ref=searchresults

https://github.com/search?utf8=%E2%9C%93&q=org%3Aowlcs+oraclejdk8&type=Code&ref=searchresults

We can swap these as soon as it becomes available. If we have particular 
worries about explicitly testing openjdk8 we can set up a jenkins job.

**Comment by kltm** [comment]
:sigh: Well, nevermind then--I hadn't realized that this was a limitation in Travis.
...and my opinion of travis has managed to click even lower...
