### ISSUE TITLE
Move configuration over to go-site

### ISSUE THREAD

**Issue by cmungall** [cmungall/go-graphstore#14]
The current makefile is incomplete (only a subset of GAFs), and is duplicative with the new go pipeline; see the README

https://github.com/geneontology/go-site/tree/master/pipeline

We should roll in the generation of the ttl files into the main GO release pipeline, so that the ttls are available for download by others.

**Comment by dougli1sqrd** [comment]
So to be clear:

We basically want the go-site pipeline Makefile to perform the duties of the Makefile in go-graphstore? So gather and build the blazegraph jars, download and generate rdf files, run rdfox and import ontologies inferred and otherwise into the blazegraph? This should be integrated into the go-site Makefile at some point during the build?

**Comment by dougli1sqrd** [comment]
Should I consider this closed? We just have to refine it on the go-site side now.

**Comment by kltm** [comment]
@cmungall and myself may have different opinions about this. We should probably touch bases when @cmungall gets back on Friday or Monday.

**Comment by cmungall** [comment]
yes

**Comment by cmungall** [comment]
@dougli1sqrd will move sparql queries over to example-queries OR go-site for ones that should be in the pipeline.

Then check rest of tickets in this repo, close tickets, then deprecated/close repo
